CREATE DATABASE IF NOT EXISTS problem_suggest;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'Tiozo#3715';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'tiozo'@'%' IDENTIFIED BY 'Tiozo#3715';
GRANT ALL PRIVILEGES ON *.* TO 'tiozo'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;