spring.application.name=FCJ-Problem_Suggest

server.address=127.0.0.1
server.port=8080

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.username=root
spring.datasource.password=Tiozo#3715
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/problem_suggest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

storage.type=s3

aws.s3.bucket=${AWS_S3_BUCKET}
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}